INFO 2025-06-05 11:55:28 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2025-06-05 11:55:28 FaceAlignModelLoader.py: 16] Start to analyze the face landmark model, model path: face_sdk/models, model category: face_alignment，model name: face_alignment_1.0
INFO 2025-06-05 11:55:28 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-06-05 11:55:28 FaceAlignModelLoader.py: 25] The model failed to load, please check the model path: face_sdk/models\face_alignment\face_alignment_1.0\face_landmark_pfld.pkl!
INFO 2025-06-05 14:35:38 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2025-06-05 14:35:38 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-06-05 14:35:38 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2025-06-05 14:35:38 FaceAlignModelLoader.py: 16] Start to analyze the face landmark model, model path: face_sdk/models, model category: face_alignment，model name: face_alignment_1.0
INFO 2025-06-05 14:35:38 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-06-05 14:35:38 FaceAlignModelLoader.py: 29] Successfully loaded the face landmark model!
INFO 2025-06-05 14:35:38 FaceRecModelLoader.py: 16] Start to analyze the face recognition model, model path: face_sdk/models, model category: face_recognition，model name: face_recognition_1.0
INFO 2025-06-05 14:35:38 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-06-05 14:35:38 FaceRecModelLoader.py: 30] Successfully loaded the face recognition model!
INFO 2025-06-05 14:37:39 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2025-06-05 14:37:39 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-06-05 14:37:39 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2025-06-05 14:37:39 FaceAlignModelLoader.py: 16] Start to analyze the face landmark model, model path: face_sdk/models, model category: face_alignment，model name: face_alignment_1.0
INFO 2025-06-05 14:37:39 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-06-05 14:37:40 FaceAlignModelLoader.py: 29] Successfully loaded the face landmark model!
INFO 2025-06-05 14:37:40 FaceRecModelLoader.py: 16] Start to analyze the face recognition model, model path: face_sdk/models, model category: face_recognition，model name: face_recognition_1.0
INFO 2025-06-05 14:37:40 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-06-05 14:37:40 FaceRecModelLoader.py: 30] Successfully loaded the face recognition model!
INFO 2025-06-05 14:37:40 _universal.py: 511] Request URL: 'https://faceatidb.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.6.0 Python/3.11.9 (Windows-10-10.0.26100-SP0)'
No body was attached to the request
DEBUG 2025-06-05 14:37:40 connectionpool.py: 1049] Starting new HTTPS connection (1): faceatidb.documents.azure.com:443
DEBUG 2025-06-05 14:37:41 connectionpool.py: 544] https://faceatidb.documents.azure.com:443 "GET / HTTP/1.1" 200 None
INFO 2025-06-05 14:37:41 _universal.py: 547] Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Thu, 05 Jun 2025 19:37:41 GMT'
INFO 2025-06-05 14:37:41 _universal.py: 511] Request URL: 'https://faceatidb.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.6.0 Python/3.11.9 (Windows-10-10.0.26100-SP0)'
No body was attached to the request
DEBUG 2025-06-05 14:37:41 connectionpool.py: 1049] Starting new HTTPS connection (1): faceatidb.documents.azure.com:443
DEBUG 2025-06-05 14:37:42 connectionpool.py: 544] https://faceatidb.documents.azure.com:443 "GET / HTTP/1.1" 200 None
INFO 2025-06-05 14:37:42 _universal.py: 547] Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Thu, 05 Jun 2025 19:37:41 GMT'
INFO 2025-06-05 14:38:09 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2025-06-05 14:38:09 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-06-05 14:38:10 FaceDetModelLoader.py: 34] Successfully loaded the face detection model!
INFO 2025-06-05 14:38:10 FaceAlignModelLoader.py: 16] Start to analyze the face landmark model, model path: face_sdk/models, model category: face_alignment，model name: face_alignment_1.0
INFO 2025-06-05 14:38:10 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-06-05 14:38:10 FaceAlignModelLoader.py: 29] Successfully loaded the face landmark model!
INFO 2025-06-05 14:38:10 FaceRecModelLoader.py: 16] Start to analyze the face recognition model, model path: face_sdk/models, model category: face_recognition，model name: face_recognition_1.0
INFO 2025-06-05 14:38:10 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-06-05 14:38:10 FaceRecModelLoader.py: 30] Successfully loaded the face recognition model!
INFO 2025-06-05 14:38:10 _universal.py: 511] Request URL: 'https://faceatidb.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.6.0 Python/3.11.9 (Windows-10-10.0.26100-SP0)'
No body was attached to the request
DEBUG 2025-06-05 14:38:10 connectionpool.py: 1049] Starting new HTTPS connection (1): faceatidb.documents.azure.com:443
DEBUG 2025-06-05 14:38:11 connectionpool.py: 544] https://faceatidb.documents.azure.com:443 "GET / HTTP/1.1" 200 None
INFO 2025-06-05 14:38:11 _universal.py: 547] Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Thu, 05 Jun 2025 19:38:10 GMT'
INFO 2025-06-05 14:38:11 _universal.py: 511] Request URL: 'https://faceatidb.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.6.0 Python/3.11.9 (Windows-10-10.0.26100-SP0)'
No body was attached to the request
DEBUG 2025-06-05 14:38:11 connectionpool.py: 1049] Starting new HTTPS connection (1): faceatidb.documents.azure.com:443
DEBUG 2025-06-05 14:38:11 connectionpool.py: 544] https://faceatidb.documents.azure.com:443 "GET / HTTP/1.1" 200 None
